### ISSUE TITLE
van-nav-bar   fixed    与  van-tabs  sticky   吸顶冲突

### ISSUE THREAD

**Issue by DarkLove** [youzan/vant-issue-generater#17]
van-nav-bar   fixed    与  van-tabs  sticky   产生冲突，position: fixed;  top: 0;  van-tabs 被 van-nav-bar遮挡，大部分手机端的情况，
tabs的吸顶应该在van-nav-bar的下方。我修改了van-tabs 吸顶的高度，但是切换tab的时候，那个css就会消失了。这个问题希望解决一下。

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
