### ISSUE TITLE
van-nav-bar fixed 与 van-tabs sticky 吸顶冲突

### ISSUE THREAD

**Issue by DarkLove** [youzan/vant-issue-generater#18]
**设备 / 浏览器**
iphonex，安卓机，谷歌浏览器等等

**Vant 版本**
2.12.9

**Vue 版本**
3.0.7

重现链接
[](https://youzan.github.io/vant/#/zh-CN/tab)

**描述问题**
van-nav-bar fixed 与 van-tabs sticky 吸顶冲突，  van-tabs 被 van-nav-bar遮挡，大部分手机端的情况，
tabs的吸顶应该在van-nav-bar的下方。这个问题希望解决一下。

**Comment by chenjiahan** [comment]
请到 vant 仓库下按照模板反馈，并提供 codesandbox 复现链接，这里不是反馈问题的仓库。
