### ISSUE TITLE
哥，看看能不能实现一下这个需求，做项目时刚好遇到了这种特殊的奇葩情况？

### ISSUE THREAD

**Issue by qixinyu520** [youzan/vant-issue-generater#30]
vant选择器里有一个value-key的属性，这个是配置选项对象中，选项文字对应的键名，而且是只能写字符串的形式，比如说对象的某个属性name啥的，但是我遇过了这么个奇葩情况，就是需要展示的对象的属性还是对象，需要展示对象的对象的属性，类似object.name的这种。我曾与后台讨论能不能不要把该属性整成对象给我，他说不好拆分这个属性，只能以对象的形式给我这个属性。而value-key里只能写name,如果写object的name就识别不出来的了，为此挺苦恼的。大哥看看能不能针对这种情况，能不能有个另外一种的处理方式！谢谢！
![image](https://user-images.githubusercontent.com/31921532/132014732-540ceeca-1100-4471-b08c-692325724788.png)
![image](https://user-images.githubusercontent.com/31921532/132014806-67430be0-dfab-4f32-9e37-ca29adf6f481.png)

**Comment by chenjiahan** [comment]
你可以自行转化一下数据结构喔，组件这边没有计划支持
